# GitHub Pages compatible configuration
theme: minima

# Site settings
title: "Yulei Liu - DevSecOps Professional"
email: yulei@ausmartway.com
description: > # this means to ignore newlines until "baseurl:"
  DevSecOps and Cloud Infrastructure Professional. Monitoring/DevSecOps/AI practitioner 
  specializing in HashiCorp ecosystem, Infrastructure as Code, and cloud security.
  Based in Sydney, Australia.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ausmartway.github.io" # the base hostname & protocol for your site

# Author info
author:
  name: Yulei Liu
  email: yulei@ausmartway.com

# Social networking links
github_username: ausmartway
linkedin_username: yulei-liu

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Header pages
header_pages:
  - about.md
  - projects.md

# Minima theme settings
minima:
  skin: dark
  social_links:
    github: ausmartway
    linkedin: yulei-liu

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/